import Head from "next/head";
import Header from "../components/Header";
import LandingPage from "../components/LandingPage";

export default function Home() {
  return (
    <div className="min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <LandingPage />
    </div>
  );
}
